name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [
          3.6,
          3.7,
          3.8,
          3.9,
          "3.10",
          "3.11",
          "3.12",
          latest
        ]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Print Python information
        run: python --version
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Verify code format with black
        run: |
          pip install black
          black . --check
      - name: Verify code linting with pylint
        run: |
          pip install pylint
          cd src
          PYTHONPATH=. pylint --disable=R,C *
          cd ..
        if: matrix.python-version == '3.11'
      - name: Run unit tests
        run: python setup.py test
        if: ${{ !contains(fromJson('["3.9", "3.10", "3.11", "3.12","latest"]'), matrix.python-version) }}
      - name: Run unit tests with pytest
        run: |
          pip install pytest
          pytest
