name: Main Workflow
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10", "3.11"]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
        name: Checkout code from repository
      - run: python --version
        name: Python version
      - run: pip install -r requirements.txt
        name: Install Python dependencies
      - run: |
          pip install black
          black . --check
        name: Verify code format with black
      - run: python setup.py test
        name: Run unit tests
